<a href="https://colab.research.google.com/github/Unstinted/Data-Analysis/blob/main/Fraud_Detection_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [29]:
import pandas as pd
import numpy as np
data = pd.read_csv("credit_card.csv")

In [30]:
data.head(200)

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
0,1,PAYMENT,9839.64,C1231006815,170136.00,160296.36,M1979787155,0.00,0.00,0.0,0.0
1,1,PAYMENT,1864.28,C1666544295,21249.00,19384.72,M2044282225,0.00,0.00,0.0,0.0
2,1,TRANSFER,181.00,C1305486145,181.00,0.00,C553264065,0.00,0.00,1.0,0.0
3,1,CASH_OUT,181.00,C840083671,181.00,0.00,C38997010,21182.00,0.00,1.0,0.0
4,1,PAYMENT,11668.14,C2048537720,41554.00,29885.86,M1230701703,0.00,0.00,0.0,0.0
5,1,PAYMENT,7817.71,C90045638,53860.00,46042.29,M573487274,0.00,0.00,0.0,0.0
6,1,PAYMENT,7107.77,C154988899,183195.00,176087.23,M408069119,0.00,0.00,0.0,0.0
7,1,PAYMENT,7861.64,C1912850431,176087.23,168225.59,M633326333,0.00,0.00,0.0,0.0
8,1,PAYMENT,4024.36,C1265012928,2671.00,0.00,M1176932104,0.00,0.00,0.0,0.0
9,1,DEBIT,5337.77,C712410124,41720.00,36382.23,C195600860,41898.00,40348.79,0.0,0.0
10,1,DEBIT,9644.94,C1900366749,4465.00,0.00,C997608398,10845.00,157982.12,0.0,0.0
11,1,PAYMENT,3099.97,C249177573,20771.00,17671.03,M2096539129,0.00,0.00,0.0,0.0
12,1,PAYMENT,2560.74,C1648232591,5070.00,2509.26,M972865270,0.00,0.00,0.0,0.0
13,1,PAYMENT,11633.76,C1716932897,10127.00,0.00,M801569151,0.00,0.00,0.0,0.0
14,1,PAYMENT,4098.78,C1026483832,503264.00,499165.22,M1635378213,0.00,0.00,0.0,0.0
15,1,CASH_OUT,229133.94,C905080434,15325.00,0.00,C476402209,5083.00,51513.44,0.0,0.0
16,1,PAYMENT,1563.82,C761750706,450.00,0.00,M1731217984,0.00,0.00,0.0,0.0
17,1,PAYMENT,1157.86,C1237762639,21156.00,19998.14,M1877062907,0.00,0.00,0.0,0.0
18,1,PAYMENT,671.64,C2033524545,15123.00,14451.36,M473053293,0.00,0.00,0.0,0.0
19,1,TRANSFER,215310.30,C1670993182,705.00,0.00,C1100439041,22425.00,0.00,0.0,0.0
20,1,PAYMENT,1373.43,C20804602,13854.00,12480.57,M1344519051,0.00,0.00,0.0,0.0
21,1,DEBIT,9302.79,C1566511282,11299.00,1996.21,C1973538135,29832.00,16896.70,0.0,0.0
22,1,DEBIT,1065.41,C1959239586,1817.00,751.59,C515132998,10330.00,0.00,0.0,0.0
23,1,PAYMENT,3876.41,C504336483,67852.00,63975.59,M1404932042,0.00,0.00,0.0,0.0
24,1,TRANSFER,311685.89,C1984094095,10835.00,0.00,C932583850,6267.00,2719172.89,0.0,0.0
25,1,PAYMENT,6061.13,C1043358826,443.00,0.00,M1558079303,0.00,0.00,0.0,0.0
26,1,PAYMENT,9478.39,C1671590089,116494.00,107015.61,M58488213,0.00,0.00,0.0,0.0
27,1,PAYMENT,8009.09,C1053967012,10968.00,2958.91,M295304806,0.00,0.00,0.0,0.0
28,1,PAYMENT,8901.99,C1632497828,2958.91,0.00,M33419717,0.00,0.00,0.0,0.0
29,1,PAYMENT,9920.52,C764826684,0.00,0.00,M1940055334,0.00,0.00,0.0,0.0
30,1,PAYMENT,3448.92,C2103763750,0.00,0.00,M335107734,0.00,0.00,0.0,0.0
31,1,PAYMENT,4206.84,C215078753,0.00,0.00,M1757317128,0.00,0.00,0.0,0.0
32,1,PAYMENT,5885.56,C840514538,0.00,0.00,M1804441305,0.00,0.00,0.0,0.0
33,1,PAYMENT,5307.88,C1768242710,0.00,0.00,M1971783162,0.00,0.00,0.0,0.0
34,1,PAYMENT,5031.22,C247113419,0.00,0.00,M151442075,0.00,0.00,0.0,0.0
35,1,PAYMENT,24213.67,C1238616099,0.00,0.00,M70695990,0.00,0.00,0.0,0.0
36,1,PAYMENT,8603.42,C1608633989,253.00,0.00,M1615617512,0.00,0.00,0.0,0.0
37,1,PAYMENT,2791.42,C923341586,300481.00,297689.58,M107994825,0.00,0.00,0.0,0.0
38,1,PAYMENT,7413.54,C1470868839,297689.58,290276.03,M1426725223,0.00,0.00,0.0,0.0
39,1,PAYMENT,3295.19,C711197015,233633.00,230337.81,M1384454980,0.00,0.00,0.0,0.0
40,1,PAYMENT,1684.81,C1481594086,297.00,0.00,M1569435561,0.00,0.00,0.0,0.0
41,1,DEBIT,5758.59,C1466917878,32604.00,26845.41,C1297685781,209699.00,16997.22,0.0,0.0
42,1,CASH_OUT,110414.71,C768216420,26845.41,0.00,C1509514333,288800.00,2415.16,0.0,0.0
43,1,PAYMENT,7823.46,C260084831,998.00,0.00,M267814113,0.00,0.00,0.0,0.0
44,1,PAYMENT,5086.48,C598357562,0.00,0.00,M1593224710,0.00,0.00,0.0,0.0
45,1,PAYMENT,5281.48,C1440738283,152019.00,146737.52,M1849015357,0.00,0.00,0.0,0.0
46,1,PAYMENT,13875.98,C484199463,15818.00,1942.02,M2008106788,0.00,0.00,0.0,0.0
47,1,CASH_OUT,56953.90,C1570470538,1942.02,0.00,C824009085,70253.00,64106.18,0.0,0.0
48,1,CASH_OUT,5346.89,C512549200,0.00,0.00,C248609774,652637.00,6453430.91,0.0,0.0
49,1,PAYMENT,2204.04,C1615801298,586.00,0.00,M490391704,0.00,0.00,0.0,0.0
50,1,PAYMENT,2641.47,C460570271,23053.00,20411.53,M1653361344,0.00,0.00,0.0,0.0
51,1,CASH_OUT,23261.30,C2072313080,20411.53,0.00,C2001112025,25742.00,0.00,0.0,0.0
52,1,PAYMENT,2330.64,C816944408,203543.00,201212.36,M909132503,0.00,0.00,0.0,0.0
53,1,PAYMENT,1614.64,C912966811,41276.00,39661.36,M1792384402,0.00,0.00,0.0,0.0
54,1,PAYMENT,9164.71,C1458621573,47235.77,38071.06,M1658980982,0.00,0.00,0.0,0.0
55,1,PAYMENT,2970.97,C46941357,38071.06,35100.09,M1152606315,0.00,0.00,0.0,0.0
56,1,PAYMENT,38.66,C343345308,16174.00,16135.34,M1714688478,0.00,0.00,0.0,0.0
57,1,PAYMENT,2252.44,C104716441,1627.00,0.00,M1506951181,0.00,0.00,0.0,0.0
58,1,TRANSFER,62610.80,C1976401987,79114.00,16503.20,C1937962514,517.00,8383.29,0.0,0.0
59,1,DEBIT,5529.13,C867288517,8547.00,3017.87,C242131142,10206.00,0.00,0.0,0.0
60,1,CASH_OUT,82940.31,C1528834618,3017.87,0.00,C476800120,132372.00,49864.36,0.0,0.0
61,1,DEBIT,4510.22,C280615803,10256.00,5745.78,C1254526270,10697.00,0.00,0.0,0.0
62,1,DEBIT,8727.74,C166694583,882770.00,874042.26,C1129670968,12636.00,0.00,0.0,0.0
63,1,PAYMENT,2599.46,C885910946,874042.26,871442.79,M1860591867,0.00,0.00,0.0,0.0
64,1,DEBIT,4874.49,C811207775,153.00,0.00,C1971489295,253104.00,0.00,0.0,0.0
65,1,PAYMENT,6440.78,C1161148117,2192.00,0.00,M516875052,0.00,0.00,0.0,0.0
66,1,PAYMENT,4910.14,C1131592118,41551.00,36640.86,M589987187,0.00,0.00,0.0,0.0
67,1,PAYMENT,6444.64,C1262609629,12019.00,5574.36,M587180314,0.00,0.00,0.0,0.0
68,1,DEBIT,5149.66,C1955990522,4782.00,0.00,C1330106945,52752.00,24044.18,0.0,0.0
69,1,PAYMENT,7292.16,C69673470,216827.00,209534.84,M1082411691,0.00,0.00,0.0,0.0
70,1,CASH_OUT,47458.86,C527211736,209534.84,162075.98,C2096057945,52120.00,0.00,0.0,0.0
71,1,CASH_OUT,136872.92,C1533123860,162075.98,25203.05,C766572210,217806.00,0.00,0.0,0.0
72,1,CASH_OUT,94253.33,C1718906711,25203.05,0.00,C977993101,99773.00,965870.05,0.0,0.0
73,1,PAYMENT,2998.04,C71802912,12030.00,9031.96,M2134271532,0.00,0.00,0.0,0.0
74,1,PAYMENT,3454.08,C686349795,9031.96,5577.88,M1831010686,0.00,0.00,0.0,0.0
75,1,PAYMENT,4316.20,C1423768154,10999.00,6682.80,M404222443,0.00,0.00,0.0,0.0
76,1,PAYMENT,2131.84,C1987977423,224.00,0.00,M61073295,0.00,0.00,0.0,0.0
77,1,PAYMENT,12986.61,C807322507,23350.00,10363.39,M396485834,0.00,0.00,0.0,0.0
78,1,TRANSFER,42712.39,C283039401,10363.39,0.00,C1330106945,57901.66,24044.18,0.0,0.0
79,1,TRANSFER,77957.68,C207471778,0.00,0.00,C1761291320,94900.00,22233.65,0.0,0.0
80,1,TRANSFER,17231.46,C1243171897,0.00,0.00,C783286238,24672.00,0.00,0.0,0.0
81,1,TRANSFER,78766.03,C1376151044,0.00,0.00,C1749186397,103772.00,277515.05,0.0,0.0
82,1,TRANSFER,224606.64,C873175411,0.00,0.00,C766572210,354678.92,0.00,0.0,0.0
83,1,TRANSFER,125872.53,C1443967876,0.00,0.00,C392292416,348512.00,3420103.09,0.0,0.0
84,1,TRANSFER,379856.23,C1449772539,0.00,0.00,C1590550415,900180.00,19169204.93,0.0,0.0
85,1,TRANSFER,1505626.01,C926859124,0.00,0.00,C665576141,29031.00,5515763.34,0.0,0.0
86,1,TRANSFER,554026.99,C1603696865,0.00,0.00,C766572210,579285.56,0.00,0.0,0.0
87,1,TRANSFER,147543.10,C12905860,0.00,0.00,C1359044626,223220.00,16518.36,0.0,0.0
88,1,TRANSFER,761507.39,C412788346,0.00,0.00,C1590550415,1280036.23,19169204.93,0.0,0.0
89,1,TRANSFER,1429051.47,C1520267010,0.00,0.00,C1590550415,2041543.62,19169204.93,0.0,0.0
90,1,TRANSFER,358831.92,C908084672,0.00,0.00,C392292416,474384.53,3420103.09,0.0,0.0
91,1,TRANSFER,367768.40,C288306765,0.00,0.00,C1359044626,370763.10,16518.36,0.0,0.0
92,1,TRANSFER,209711.11,C1556867940,0.00,0.00,C1509514333,399214.71,2415.16,0.0,0.0
93,1,TRANSFER,583848.46,C1839168128,0.00,0.00,C1286084959,667778.00,2107778.11,0.0,0.0
94,1,TRANSFER,1724887.05,C1495608502,0.00,0.00,C1590550415,3470595.10,19169204.93,0.0,0.0
95,1,TRANSFER,710544.77,C835773569,0.00,0.00,C1359044626,738531.50,16518.36,0.0,0.0
96,1,TRANSFER,581294.26,C843299092,0.00,0.00,C1590550415,5195482.15,19169204.93,0.0,0.0
97,1,TRANSFER,11996.58,C605982374,0.00,0.00,C1225616405,40255.00,0.00,0.0,0.0
98,1,PAYMENT,2875.10,C1412322831,15443.00,12567.90,M1651262695,0.00,0.00,0.0,0.0
99,1,PAYMENT,8586.98,C1305004711,3763.00,0.00,M494077446,0.00,0.00,0.0,0.0
100,1,PAYMENT,871.75,C1003206025,19869.00,18997.25,M989889899,0.00,0.00,0.0,0.0
101,1,PAYMENT,1035.36,C806813022,71636.00,70600.64,M902860396,0.00,0.00,0.0,0.0
102,1,PAYMENT,1063.53,C1406206626,83084.00,82020.47,M1816522350,0.00,0.00,0.0,0.0
103,1,PAYMENT,1019.90,C1799230133,204237.00,203217.10,M1521238608,0.00,0.00,0.0,0.0
104,1,PAYMENT,4059.38,C20156341,26304.00,22244.62,M1111897955,0.00,0.00,0.0,0.0
105,1,PAYMENT,1876.44,C1509309988,182.00,0.00,M1643141512,0.00,0.00,0.0,0.0
106,1,CASH_OUT,28404.60,C2091072548,0.00,0.00,C1282788025,51744.00,0.00,0.0,0.0
107,1,CASH_OUT,75405.10,C263053820,0.00,0.00,C1870252780,104209.00,46462.23,0.0,0.0
108,1,CASH_OUT,50101.88,C1740826931,0.00,0.00,C97730845,67684.00,9940339.29,0.0,0.0
109,1,CASH_OUT,14121.82,C69062746,0.00,0.00,C100555887,52679.00,10963.66,0.0,0.0
110,1,CASH_OUT,78292.91,C1631227617,0.00,0.00,C1983747920,121112.00,95508.95,0.0,0.0
111,1,CASH_OUT,176149.90,C24650043,0.00,0.00,C736709391,259813.00,46820.71,0.0,0.0
112,1,CASH_OUT,212228.35,C1896074070,0.00,0.00,C401424608,429747.00,1178808.14,0.0,0.0
113,1,CASH_OUT,85423.63,C460741164,0.00,0.00,C1590550415,5776776.41,19169204.93,0.0,0.0
114,1,CASH_OUT,11648.50,C781091365,0.00,0.00,C985934102,260976.00,971418.91,0.0,0.0
115,1,PAYMENT,6165.58,C1858015030,20925.00,14759.42,M25764044,0.00,0.00,0.0,0.0
116,1,PAYMENT,3705.83,C671596011,41903.46,38197.63,M1925352804,0.00,0.00,0.0,0.0
117,1,CASH_OUT,419801.40,C1687354037,38197.63,0.00,C33524623,499962.00,1517262.16,0.0,0.0
118,1,CASH_OUT,335416.51,C743778731,144478.00,0.00,C575335780,295.00,52415.15,0.0,0.0
119,1,PAYMENT,3372.29,C967323951,41398.00,38025.71,M1600594643,0.00,0.00,0.0,0.0
120,1,PAYMENT,661.43,C743648472,14078.00,13416.57,M692998280,0.00,0.00,0.0,0.0
121,1,DEBIT,864.68,C1368862151,69836.00,68971.32,C20671747,12040.00,43691.09,0.0,0.0
122,1,PAYMENT,1203.44,C922807452,29941.00,28737.56,M33563464,0.00,0.00,0.0,0.0
123,1,TRANSFER,330757.04,C1494346128,103657.00,0.00,C564160838,79676.00,1254956.07,0.0,0.0
124,1,PAYMENT,1915.43,C822087264,11450.00,9534.57,M30699728,0.00,0.00,0.0,0.0
125,1,PAYMENT,8.73,C38603201,81313.00,81304.27,M1422273905,0.00,0.00,0.0,0.0
126,1,DEBIT,3058.80,C1694784135,18138.00,15079.20,C801197928,11054.00,8917.54,0.0,0.0
127,1,PAYMENT,5154.97,C1207231495,9476.00,4321.03,M756936249,0.00,0.00,0.0,0.0
128,1,PAYMENT,5213.25,C1221981006,36380.00,31166.75,M264394929,0.00,0.00,0.0,0.0
129,1,PAYMENT,5392.75,C1878413714,50757.00,45364.25,M769132147,0.00,0.00,0.0,0.0
130,1,PAYMENT,25.12,C1257299717,61663.00,61637.88,M1474957626,0.00,0.00,0.0,0.0
131,1,PAYMENT,17150.89,C181252244,61637.88,44486.99,M1733022752,0.00,0.00,0.0,0.0
132,1,TRANSFER,679502.24,C722417467,290.00,0.00,C451111351,171866.00,3940085.21,0.0,0.0
133,1,TRANSFER,177652.91,C753631393,23720.00,0.00,C716157500,55.00,4894.45,0.0,0.0
134,1,PAYMENT,5443.26,C1262869688,236997.00,231553.74,M1914108708,0.00,0.00,0.0,0.0
135,1,PAYMENT,244.87,C544386226,257978.49,257733.62,M1357700757,0.00,0.00,0.0,0.0
136,1,PAYMENT,8281.57,C900298796,257733.62,249452.05,M1889757798,0.00,0.00,0.0,0.0
137,1,PAYMENT,1175.59,C1166106620,20509.00,19333.41,M1932470703,0.00,0.00,0.0,0.0
138,1,PAYMENT,1097.74,C221861886,24866.00,23768.26,M1713568869,0.00,0.00,0.0,0.0
139,1,TRANSFER,184986.80,C697508322,39588.00,0.00,C1688019098,52340.00,97263.78,0.0,0.0
140,1,PAYMENT,1718.29,C603658030,117811.00,116092.71,M1689924104,0.00,0.00,0.0,0.0
141,1,PAYMENT,3671.32,C361380654,100094.00,96422.68,M631673932,0.00,0.00,0.0,0.0
142,1,DEBIT,3580.26,C1579132337,2565.00,0.00,C1321640594,21185.00,18910.85,0.0,0.0
143,1,PAYMENT,8550.90,C1795225096,40060.00,31509.10,M790094605,0.00,0.00,0.0,0.0
144,1,PAYMENT,9753.55,C1048712791,60829.00,51075.45,M487792155,0.00,0.00,0.0,0.0
145,1,PAYMENT,3026.98,C1909398279,31139.00,28112.02,M1632670136,0.00,0.00,0.0,0.0
146,1,CASH_OUT,467177.03,C1338905451,28112.02,0.00,C1170794006,975121.00,22190.99,0.0,0.0
147,1,DEBIT,3875.99,C1252540239,259138.00,255262.01,C1509514333,608925.82,2415.16,0.0,0.0
148,1,PAYMENT,2148.89,C1136005694,31213.00,29064.11,M638486177,0.00,0.00,0.0,0.0
149,1,PAYMENT,466.97,C426019904,80030.00,79563.03,M314411620,0.00,0.00,0.0,0.0
150,1,CASH_OUT,154139.72,C1642679791,79563.03,0.00,C564160838,410433.04,1254956.07,0.0,0.0
151,1,CASH_OUT,82685.93,C855700733,0.00,0.00,C392292416,833216.44,3420103.09,0.0,0.0
152,1,CASH_OUT,83857.23,C247162961,0.00,0.00,C1297685781,215457.59,16997.22,0.0,0.0
153,1,CASH_OUT,99109.77,C1890266440,0.00,0.00,C1297685781,299314.82,16997.22,0.0,0.0
154,1,CASH_OUT,187726.67,C1527152775,0.00,0.00,C747464370,190573.00,1567434.81,0.0,0.0
155,1,CASH_OUT,281339.92,C1863655430,0.00,0.00,C1509514333,612801.81,2415.16,0.0,0.0
156,1,CASH_OUT,186447.51,C976827477,0.00,0.00,C1590550415,5862200.03,19169204.93,0.0,0.0
157,1,CASH_OUT,81029.86,C324112183,0.00,0.00,C288665596,105343.00,8496.61,0.0,0.0
158,1,CASH_OUT,139054.95,C2092709730,0.00,0.00,C1749186397,182538.03,277515.05,0.0,0.0
159,1,CASH_OUT,154716.20,C980364771,0.00,0.00,C453211571,187433.00,3461666.05,0.0,0.0
160,1,CASH_OUT,53631.83,C1233595751,0.00,0.00,C757108857,83244.00,0.00,0.0,0.0
161,1,CASH_OUT,289645.52,C1446001495,0.00,0.00,C1023714065,871442.79,1412484.09,0.0,0.0
162,1,CASH_OUT,267148.82,C1261044180,0.00,0.00,C401424608,641975.35,1178808.14,0.0,0.0
163,1,CASH_OUT,47913.58,C141110631,0.00,0.00,C240650537,51304.00,0.00,0.0,0.0
164,1,CASH_OUT,193605.38,C2029372696,0.00,0.00,C1971489295,249452.05,0.00,0.0,0.0
165,1,CASH_OUT,344464.40,C793293778,0.00,0.00,C766572210,1133312.56,0.00,0.0,0.0
166,1,CASH_OUT,169409.87,C888611662,0.00,0.00,C401424608,909124.16,1178808.14,0.0,0.0
167,1,CASH_OUT,25793.74,C1966355106,0.00,0.00,C476800120,215312.31,49864.36,0.0,0.0
168,1,CASH_OUT,114712.48,C599782425,0.00,0.00,C1209271652,145400.00,0.00,0.0,0.0
169,1,CASH_OUT,89038.75,C1233327519,0.00,0.00,C2083562754,189808.00,1186556.81,0.0,0.0
170,1,CASH_OUT,1341.58,C1155769010,0.00,0.00,C557041912,80341.00,557537.26,0.0,0.0
171,1,CASH_OUT,44443.08,C269892014,0.00,0.00,C1590550415,6048647.54,19169204.93,0.0,0.0
172,1,CASH_OUT,34729.64,C1280641161,0.00,0.00,C1435804085,44853.00,96.88,0.0,0.0
173,1,CASH_OUT,105979.34,C489411441,0.00,0.00,C736709391,435962.90,46820.71,0.0,0.0
174,1,CASH_OUT,57794.61,C1141113940,0.00,0.00,C240650537,99217.58,0.00,0.0,0.0
175,1,CASH_OUT,15918.79,C1711185459,0.00,0.00,C1854778591,24553.00,0.00,0.0,0.0
176,1,CASH_OUT,19162.08,C25936709,0.00,0.00,C885951223,60169.00,215851.28,0.0,0.0
177,1,CASH_OUT,220691.42,C1123559518,0.00,0.00,C1590550415,6093090.62,19169204.93,0.0,0.0
178,1,CASH_OUT,9536.54,C649769713,0.00,0.00,C1060830840,49161.00,130747.56,0.0,0.0
179,1,CASH_OUT,29784.06,C925150995,0.00,0.00,C920011586,63553.00,0.00,0.0,0.0
180,1,CASH_OUT,190445.51,C1760219993,0.00,0.00,C1360767589,203679.00,2107965.39,0.0,0.0
181,1,CASH_OUT,57279.11,C1800649922,0.00,0.00,C824009085,127206.90,64106.18,0.0,0.0
182,1,CASH_OUT,112086.81,C403547747,0.00,0.00,C1531333864,292728.00,55974.56,0.0,0.0
183,1,CASH_OUT,80311.89,C172215878,0.00,0.00,C434091818,87408.00,63112.23,0.0,0.0
184,1,CASH_OUT,151829.91,C873309260,0.00,0.00,C1023714065,1161088.31,1412484.09,0.0,0.0
185,1,CASH_OUT,26004.52,C1112456099,0.00,0.00,C1225616405,52251.58,0.00,0.0,0.0
186,1,CASH_OUT,3146.16,C923083575,0.00,0.00,C1504109395,9471.00,593737.38,0.0,0.0
187,1,CASH_OUT,296752.75,C589363823,0.00,0.00,C1531333864,404814.81,55974.56,0.0,0.0
188,1,CASH_OUT,191702.06,C2052457859,0.00,0.00,C985934102,272624.50,971418.91,0.0,0.0
189,1,CASH_OUT,365510.05,C1299327689,0.00,0.00,C564160838,564572.76,1254956.07,0.0,0.0
190,1,CASH_OUT,202332.08,C1408279755,0.00,0.00,C453211571,342149.20,3461666.05,0.0,0.0
191,1,CASH_OUT,55105.90,C2007486296,0.00,0.00,C932583850,317952.89,2719172.89,0.0,0.0
192,1,CASH_OUT,171508.59,C1033348658,0.00,0.00,C1971489295,443057.43,0.00,0.0,0.0
193,1,CASH_OUT,178439.26,C1634723627,0.00,0.00,C2083562754,278846.75,1186556.81,0.0,0.0
194,1,CASH_OUT,88834.86,C938463537,0.00,0.00,C985934102,464326.57,971418.91,0.0,0.0
195,1,CASH_OUT,210370.09,C2121995675,0.00,0.00,C1170794006,1442298.03,22190.99,0.0,0.0
196,1,CASH_OUT,36437.06,C2120063568,0.00,0.00,C1740000325,154606.00,1363368.51,0.0,0.0
197,1,CASH_OUT,82691.56,C1620409359,0.00,0.00,C248609774,657983.89,6453430.91,0.0,0.0
198,1,CASH_OUT,338767.10,C691691381,0.00,0.00,C453211571,544481.28,3461666.05,0.0,0.0
199,1,CASH_OUT,187728.59,C264978436,0.00,0.00,C1360767589,394124.51,2107965.39,0.0,0.0

In [31]:
#Now, let’s have a look at whether this dataset has any null values or not:
print(data.isnull().sum())

step              0
type              0
amount            0
nameOrig          0
oldbalanceOrg     0
newbalanceOrig    0
nameDest          0
oldbalanceDest    0
newbalanceDest    1
isFraud           1
isFlaggedFraud    1
dtype: int64

In [32]:
#Fill null value with 0
data.fillna(0, inplace = True)

In [33]:
#Confirm Change Effect
print(data.isnull().sum())

step              0
type              0
amount            0
nameOrig          0
oldbalanceOrg     0
newbalanceOrig    0
nameDest          0
oldbalanceDest    0
newbalanceDest    0
isFraud           0
isFlaggedFraud    0
dtype: int64

In [34]:
# Exploring transaction type
data.type.value_counts()

CASH_OUT    1718959
PAYMENT     1639564
CASH_IN     1064103
TRANSFER     402960
DEBIT         30550
Name: type, dtype: int64

In [35]:
#Plot theDistribution of Transactions
type = data["type"].value_counts()
transactions = type.index
quantity = type.values

import plotly.express as px
figure = px.pie(data,
             values=quantity,
             names=transactions,hole = 0.5,
             title="Distribution of Transaction Type")
figure.show()

In [36]:
#Check correlation of Data againt isFraud Label column
correlation = data.corr(numeric_only=True)
correlation["isFraud"].sort_values(ascending=False)

isFraud           1.000000
amount            0.050514
isFlaggedFraud    0.027864
oldbalanceOrg     0.005589
newbalanceDest   -0.000416
step             -0.004686
oldbalanceDest   -0.005538
newbalanceOrig   -0.007439
Name: isFraud, dtype: float64

In [37]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4856136 entries, 0 to 4856135
Data columns (total 11 columns):
 #   Column          Dtype
---  ------          -----
 0   step            int64
 1   type            object
 2   amount          float64
 3   nameOrig        object
 4   oldbalanceOrg   float64
 5   newbalanceOrig  float64
 6   nameDest        object
 7   oldbalanceDest  float64
 8   newbalanceDest  float64
 9   isFraud         float64
 10  isFlaggedFraud  float64
dtypes: float64(7), int64(1), object(3)
memory usage: 407.5+ MB

In [38]:
# Check for the number of unique values in 'isFlaggedFraud'.
unique_values = data['isFlaggedFraud'].unique()

# Check for counts of each unique value in 'isFlaggedFraud'.
value_counts = data['isFlaggedFraud'].value_counts()

print(unique_values)
print(value_counts)

[0. 1.]
0.0    4856133
1.0          3
Name: isFlaggedFraud, dtype: int64

In [39]:
#transform the values of the isFraud column into No Fraud and Fraud labels to have a better understanding of the output
data["type"] = data["type"].map({"CASH_OUT": 1, "PAYMENT": 2,
                                 "CASH_IN": 3, "TRANSFER": 4,
                                 "DEBIT": 5})
data["isFraud"] = data["isFraud"].map({0: "No Fraud", 1: "Fraud"})
data.head()

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
0,1,2,9839.64,C1231006815,170136.0,160296.36,M1979787155,0.0,0.0,No Fraud,0.0
1,1,2,1864.28,C1666544295,21249.0,19384.72,M2044282225,0.0,0.0,No Fraud,0.0
2,1,4,181.00,C1305486145,181.0,0.00,C553264065,0.0,0.0,Fraud,0.0
3,1,1,181.00,C840083671,181.0,0.00,C38997010,21182.0,0.0,Fraud,0.0
4,1,2,11668.14,C2048537720,41554.0,29885.86,M1230701703,0.0,0.0,No Fraud,0.0

# Online Payments Fraud Detection Model

Training the classification model to classify fraud and non-fraud transactions

In [40]:
# splitting the data
from sklearn.model_selection import train_test_split
x = np.array(data[["type", "amount", "oldbalanceOrg", "newbalanceOrig"]])
y = np.array(data[["isFraud"]])

In [41]:
# training a machine learning model
from sklearn.tree import DecisionTreeClassifier
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.10, random_state=42)
model = DecisionTreeClassifier()
model.fit(xtrain, ytrain)
print(model.score(xtest, ytest))

0.9997343569172223

In [42]:
# prediction
#features = [type, amount, oldbalanceOrg, newbalanceOrig]
features = np.array([[4, 9000.60, 9000.60, 0.0]])
print(model.predict(features))

['Fraud']

In [48]:
# prediction
#features = [type, amount, oldbalanceOrg, newbalanceOrig]
features = np.array([[4, 100000.60, 6000000.60, 70000.0]])
print(model.predict(features))

['No Fraud']